import type { Venue } from "@/lib/types";

// The 12 actual confirmed host venues for FIFA World Cup 2026,
// across USA, Mexico, and Canada. Timezones are real IANA zones
// so toVenueTime() in time.ts renders correctly across DST.
export const venues: Venue[] = [
  {
    id: "ven-01",
    name: "MetLife Stadium",
    city: "New York/New Jersey",
    country: "USA",
    capacity: 82500,
    timezone: "America/New_York",
  },
  {
    id: "ven-02",
    name: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
    capacity: 80000,
    timezone: "America/Chicago",
  },
  {
    id: "ven-03",
    name: "SoFi Stadium",
    city: "Los Angeles",
    country: "USA",
    capacity: 70240,
    timezone: "America/Los_Angeles",
  },
  {
    id: "ven-04",
    name: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country: "USA",
    capacity: 71000,
    timezone: "America/New_York",
  },
  {
    id: "ven-05",
    name: "Hard Rock Stadium",
    city: "Miami",
    country: "USA",
    capacity: 64767,
    timezone: "America/New_York",
  },
  {
    id: "ven-06",
    name: "Lincoln Financial Field",
    city: "Philadelphia",
    country: "USA",
    capacity: 69796,
    timezone: "America/New_York",
  },
  {
    id: "ven-07",
    name: "Arrowhead Stadium",
    city: "Kansas City",
    country: "USA",
    capacity: 76416,
    timezone: "America/Chicago",
  },
  {
    id: "ven-08",
    name: "Levi's Stadium",
    city: "San Francisco Bay Area",
    country: "USA",
    capacity: 68500,
    timezone: "America/Los_Angeles",
  },
  {
    id: "ven-09",
    name: "Lumen Field",
    city: "Seattle",
    country: "USA",
    capacity: 69000,
    timezone: "America/Los_Angeles",
  },
  {
    id: "ven-10",
    name: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
    capacity: 83264,
    timezone: "America/Mexico_City",
  },
  {
    id: "ven-11",
    name: "Estadio BBVA",
    city: "Monterrey",
    country: "Mexico",
    capacity: 53500,
    timezone: "America/Monterrey",
  },
  {
    id: "ven-12",
    name: "BC Place",
    city: "Vancouver",
    country: "Canada",
    capacity: 54500,
    timezone: "America/Vancouver",
  },
  {
    id: "ven-13",
    name: "BMO Field",
    city: "Toronto",
    country: "Canada",
    capacity: 30000,
    timezone: "America/Toronto",
  },
];
